### ISSUE TITLE
libglvnd provided by the NVIDIA repository breaks Mesa F25 packages from version  13.0.3-4

### ISSUE THREAD

**Issue by danielkza** [negativo17/libglvnd#2]
It seems many Mesa packages in F25 started depending on libglvnd starting with version 13.0.3-4. The NVIDIA repository also provides libglvnd packages with an Epoch of 1, which seems to be holding up package upgrades.

```
Error: package mesa-libGL-13.0.3-4.fc25.x86_64 requires libglvnd-glx(x86-64), but none of the providers can be installed.
package mesa-libGL-13.0.3-4.fc25.i686 requires libglvnd-glx(x86-32), but none of the providers can be installed.
package mesa-libGLES-13.0.3-4.fc25.x86_64 requires libglvnd-gles(x86-64), but none of the providers can be installed.
package mesa-libEGL-13.0.3-4.fc25.x86_64 requires libglvnd-egl(x86-64), but none of the providers can be installed.
package mesa-libEGL-13.0.3-4.fc25.i686 requires libglvnd-egl(x86-32), but none of the providers can be installed
```

**Comment by danielkza** [comment]
Seems it was actually a bug in Fedora's packaging: https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/TWRGL66RNFHSKPK2APYXQWSW3GL7RBVO/

But whenever Mesa is actually supposed to depend on libglvnd the override might become an issue.

**Comment by scaronni** [comment]
Exactly. The package is stuck here:

https://bodhi.fedoraproject.org/updates/?packages=libglvnd

I hope it will be unblocked soon or I'll get a ton of emails and messages :(

**Comment by scaronni** [comment]
Actually I'm working with Hans, so I'm not updating the libglvnd package anymore. In Fedora 25 and up, I will remove the package and the official one from Fedora will take over.

**Comment by scaronni** [comment]
Updates coming from Fedora/EPEL official packages, deleting this repository.
